/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct singal_array {
	int size;
	int *array;
};
typedef struct singal_array singal_array;

struct double_array {
	int size;
	int *array1;
	int *array2;
};
typedef struct double_array double_array;

#define ARRAYSUM 0x0000001
#define ARRAYSUM_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM_ARRAY 1
extern  singal_array * sum_array_1(double_array *, CLIENT *);
extern  singal_array * sum_array_1_svc(double_array *, struct svc_req *);
extern int arraysum_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM_ARRAY 1
extern  singal_array * sum_array_1();
extern  singal_array * sum_array_1_svc();
extern int arraysum_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_singal_array (XDR *, singal_array*);
extern  bool_t xdr_double_array (XDR *, double_array*);

#else /* K&R C */
extern bool_t xdr_singal_array ();
extern bool_t xdr_double_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
