/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sum.h"

bool_t
xdr_singal_array (XDR *xdrs, singal_array *objp)
{
   return xdr_array(
                 xdrs,
                 (char**)(&(objp->array)),
                 &(objp->size),
                 200,
                 sizeof(int),
                 (xdrproc_t)xdr_int);
	//register int32_t *buf;

	// if (!xdr_int (xdrs, &objp->size))
	//	 return FALSE;
	// if (!xdr_pointer (xdrs, (char **)&objp->array, sizeof (int), (xdrproc_t) xdr_int))
	//	 return FALSE;
	//return TRUE;
}

bool_t
xdr_double_array (XDR *xdrs, double_array *objp)
{
  return xdr_array(
                 xdrs,
                 (char**)(&(objp->array1)),
                 &(objp->size),
                 200,
                 sizeof(int),
                 (xdrproc_t)xdr_int)
                 &&
                 xdr_array(
                 xdrs,
                 (char**)(&(objp->array2)),
                 &(objp->size),
                 200,
                 sizeof(int),
                 (xdrproc_t)xdr_int)
                 ;
	//register int32_t *buf;

	// if (!xdr_int (xdrs, &objp->size))
		 //return FALSE;
	// if (!xdr_pointer (xdrs, (char **)&objp->array1, sizeof (int), (xdrproc_t) xdr_int))
		// return FALSE;
	// if (!xdr_pointer (xdrs, (char **)&objp->array2, sizeof (int), (xdrproc_t) xdr_int))
		/// return FALSE;
	//return TRUE;
}
