/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"

singal_array *
sum_array_1_svc(double_array *argp, struct svc_req *rqstp)
{
	static singal_array  result;

	/*
	 * insert server code here
	 */
	 int i=0;
	 result.size = argp->size;
	 result.array = (int*)(malloc(sizeof(int)*argp->size));
	 for(i=0;i<argp->size;i++)
	 {
	   result.array[i] = argp->array1[i] + argp->array2[i];
	 }

	return &result;
}
