/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linked_list.h"

node *
linked_list_1_svc(list *argp, struct svc_req *rqstp)
{
	static node  result;
	node *ptr = &result;
	int i=0;
	printf("\n");
	while(argp->head1)
	{
	   if( i ==0)
	   {
	      result.data = argp->head1->data + argp->head2->data;
	      printf("%d ",result.data);
	      result.next = NULL;
	   }
	   else
	   {
	      ptr->next = (node*)(malloc(sizeof(node)));
	      ptr = ptr->next;
	      ptr->data = argp->head1->data + argp->head2->data;
	      ptr->next = NULL;
	      printf("%d ",ptr->data);
	   }
	   argp->head1 = argp->head1->next;
	   argp->head2 = argp->head2->next;
	   
	   i=1;
	}
	printf("\n");

	/*
	 * insert server code here
	 */

	return &result;
}
