/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linked_list.h"

void
linkedlist_1(char *host,list l)
{
	CLIENT *clnt;
	node  *result_1;
	list  linked_list_1_arg=l;

#ifndef	DEBUG
	clnt = clnt_create (host, LINKEDLIST, LINKEDLIST, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = linked_list_1(&linked_list_1_arg, clnt);
	if (result_1 == (node *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
	   printf("\n");
	   while(result_1)
	   {
	      printf("%d ",result_1->data);
	      result_1 = result_1->next;
	   }
	   printf("\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
print(node *l)
{
   printf("\n");
   while(l)
   {
      printf("%d ",l->data);
      l = l->next;
   }
   printf("\n");
}

int
main (int argc, char *argv[])
{
	char *host;
	list l;
	int size,i,temp;
	node *ptr1,*ptr2;
	ptr1 = (node*)(malloc(sizeof(node)));
	ptr2 = (node*)(malloc(sizeof(node)));
	l.head1 = ptr1;
	l.head2 = ptr2;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("\nEnter size : ");
	scanf("%d",&size);
	for(i=0;i<size;i++)
	{
	   scanf("%d",&temp);
	   ptr1->next = (node*)(malloc(sizeof(node)));
	   ptr1 = ptr1->next;
	   ptr1->data = temp;
	   ptr1->next = NULL;
	}
	l.head1 = l.head1->next;
	
	for(i=0;i<size;i++)
	{
	   scanf("%d",&temp);
	   ptr2->next = (node*)(malloc(sizeof(node)));
	   ptr2 = ptr2->next;
	   ptr2->data = temp;
	   ptr2->next = NULL;
	}
	l.head2 = l.head2->next;
	print(l.head1);
	print(l.head2);
	
	host = argv[1];
	linkedlist_1 (host,l);
exit (0);
}
