/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARRAY_SUM_H_RPCGEN
#define _ARRAY_SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int *array;
	int *array2;
	int size;
};
typedef struct data data;

#define ARRAYSUM 0x0000001
#define ARRAYSUM_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ARRAY_SUM 1
extern  data * array_sum_1(data *, CLIENT *);
extern  data * array_sum_1_svc(data *, struct svc_req *);
extern int arraysum_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ARRAY_SUM 1
extern  data * array_sum_1();
extern  data * array_sum_1_svc();
extern int arraysum_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARRAY_SUM_H_RPCGEN */
