/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "array_sum.h"


void
arraysum_1(char *host,data d)
{
	CLIENT *clnt;
	data  *result_1;
	int i;
	data  array_sum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARRAYSUM, ARRAYSUM_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	array_sum_1_arg.size = d.size;
	array_sum_1_arg.array = (int*)(malloc(sizeof(int)*d.size));
	array_sum_1_arg.array2 = (int*)(malloc(sizeof(int)*d.size));
	for(i=0;i<d.size;i++)
	{
		array_sum_1_arg.array[i] = d.array[i];
		array_sum_1_arg.array2[i] = d.array2[i];
		printf("\n%d ",array_sum_1_arg.array[i]);
	}
	printf("\nAFter printing\n");
	result_1 = array_sum_1(&array_sum_1_arg, clnt);
	printf("\ndata is sent : %d \n",array_sum_1_arg.size);
	printf("\ndata is sent\n");
	if (result_1 == (data *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\nSize = %d\n",result_1->size);
		printf("\n");
		for(i=0;i<result_1->size;i++)
			printf("%d ",result_1->array[i]);
		printf("\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	data d;
	int i;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("\nEnter size of array : ");
	scanf("%d",&d.size);
	d.array = (int*)(malloc(sizeof(int)*d.size));
	d.array2 = (int*)(malloc(sizeof(int)*d.size));
	for(i=0;i<d.size;i++)
	{
		scanf("%d",&(d.array[i]));
		d.array2[i] = d.array[i];
	}
	arraysum_1 (host,d);
exit (0);
}
