/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LINKED_LIST_H_RPCGEN
#define _LINKED_LIST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct node {
	int data;
	struct node *next;
};
typedef struct node node;

struct list {
	node *head1;
	node *head2;
};
typedef struct list list;

#define LINKEDLIST 0x0000000A
#define LINKEDLIST 1

#if defined(__STDC__) || defined(__cplusplus)
#define LINKED_LIST 1
extern  node * linked_list_1(list *, CLIENT *);
extern  node * linked_list_1_svc(list *, struct svc_req *);
extern int linkedlist_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LINKED_LIST 1
extern  node * linked_list_1();
extern  node * linked_list_1_svc();
extern int linkedlist_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_list (XDR *, list*);

#else /* K&R C */
extern bool_t xdr_node ();
extern bool_t xdr_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LINKED_LIST_H_RPCGEN */
